
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    static boolean isNumber(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (Character.isDigit(s.charAt(i))
                    == false) {
                return false;
            }
        }

        return true;
    }

    ArrayList<String> NameList = new ArrayList<String>();
    ArrayList<String> NumberList = new ArrayList<String>();

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pair = new javax.swing.ButtonGroup();
        message = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        inputButton = new javax.swing.JButton();
        outputField = new javax.swing.JTextField();
        outputButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radButtonName = new javax.swing.JRadioButton();
        radButtonNumber = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drop and Pick");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });
        jPanel1.add(inputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 33));

        inputButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        inputButton.setText("Drop");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });
        jPanel1.add(inputButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 64, 33));

        outputField.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        outputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        outputField.setEnabled(false);
        jPanel1.add(outputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 430, 82));

        outputButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        outputButton.setText("Pick");
        outputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputButtonActionPerformed(evt);
            }
        });
        jPanel1.add(outputButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 252, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Choose from");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        pair.add(radButtonName);
        radButtonName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        radButtonName.setText("Name");
        jPanel1.add(radButtonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 80, -1));

        pair.add(radButtonNumber);
        radButtonNumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        radButtonNumber.setText("Number");
        jPanel1.add(radButtonNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Drop and Pick");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed

    }//GEN-LAST:event_inputFieldActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed

        if (isNumber(inputField.getText())) {
            NumberList.add(inputField.getText());
        } else {
            NameList.add(inputField.getText());
        }
        inputField.setText("");

    }//GEN-LAST:event_inputButtonActionPerformed

    private void outputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputButtonActionPerformed

        if (radButtonName.isSelected()) {
//            Random random = new Random();
//            String string=random.nextInt(NameList.size());
            try {

                if (NameList.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "All the names are picked up!", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                int randomIndex = (int) (Math.random() * NameList.size());
                outputField.setText(NameList.get(randomIndex));
                NameList.remove(randomIndex);
            } catch (Exception e) {

            }
        } else {

            try {

                if (NumberList.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "All the numbers are picked up!", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                int randomIndex = (int) (Math.random() * NumberList.size());
                outputField.setText(NumberList.get(randomIndex));
                NumberList.remove(randomIndex);

            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_outputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JOptionPane message;
    private javax.swing.JButton outputButton;
    private javax.swing.JTextField outputField;
    private javax.swing.ButtonGroup pair;
    private javax.swing.JRadioButton radButtonName;
    private javax.swing.JRadioButton radButtonNumber;
    // End of variables declaration//GEN-END:variables
}
